check if SRC exists

diff --git a/ldd_jail b/ldd_jail
--- a/ldd_jail
+++ b/ldd_jail
@@ -11,6 +11,10 @@ shift
 mkdir -pv $TARGET
 
 for SRC in $@ ; do
+    if [ ! -e "$SRC" ] ; then
+        echo "$SRC not found"
+        exit 1
+    fi
     if [ -d "$SRC" ] ; then
         if echo $SRC | grep -qE '^/' ; then
             D=$(dirname $SRC)
